name = "TianJun"
uuid = "9105938f-1533-4102-bbe6-42035c5de178"
authors = ["Jun Tian <tianjun.cpp@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
